rmm_main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'rmm_main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact$', views.contact_submit, name='contact_submit')
]

web_full/urls.py
# -*- coding: utf-8 -*-
"""web_full URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('rmm_main.urls')),
    url(r'^admin/', admin.site.urls),
]

rmm_main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField(max_length=2000)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email + ' ' + self.message

rmm_main/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

rmm_main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json

from django.http import Http404
from django.shortcuts import render, render_to_response, HttpResponse
from django.template import RequestContext
from django.core.mail import send_mail

from .models import Contact
from .forms import ContactForm


def index(request):
    return render(request, 'rmm_main/index.html', {'contact': ContactForm()})


def contact_submit(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        response_msg = "Gracias %s por su solicitud de contacto. En breve nos pondremos en contacto con usted a trevés de la dirección de correo electrónico %s"
        if form.is_valid():
            name = request.POST['name']
            email = request.POST['email']
            message = request.POST['message']

            contact = Contact(name=name, email=email, message=message)
            contact.save()

            send_mail(
                'Contact form web_full',
                'Nombre: ' + name + '\nMensaje: ' + message,
                email,
                ['rafelmm@gmail.com'],
                fail_silently=False,
            )

            response_data = {'errcode': 0,
                             'message': response_msg % (name, email)}

            return HttpResponse(
                json.dumps(response_data),
                content_type="application/json"
            )

    return render_to_response('rmm_main/index.html', {'contact': ContactForm()}, RequestContext(request))

rmm_main/templates/rmm_main/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="main-container container-fluid">
    <section class="carousel slide" data-ride="carousel">
        <h1>Construimos tu sitio web</h1>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block" src="{% static 'rmm_main/img/main00.jpg' %}">
            </div>
            <div class="carousel-item">
                <img class="d-block" src="{% static 'rmm_main/img/main01.jpg' %}">
            </div>
        </div>
    </section>
    <section class="row">
        <div class="col-6 col-xl-4 d-none d-sm-block">
            <img class="section-img" src="{% static 'rmm_main/img/responsive-nobg.png' %}" alt="Accesible desde cualquier dispositivo"/>
        </div>
        <div class="col section-text">
            <h2>Accesible desde cualquier dispositivo</h2>
            <p>Nuestros diseños son responsive para que se vea de la mejor forma posible desde cualquier dispositivo. No te pierdas ni un cliente con nuestros diseños accesibles.</p>
        </div>
    </section>
    <section class="row">
        <div class="col section-text">
            <h2>Totalmente personalizado</h2>
            <p>Entendemos la web como algo totalmente personal. Por eso no usamos plantillas sinó que diseñamos la mejor web para que se adapte totalmente a las necesidades de nuestros clientes.</p>
        </div>
        <div class="col-6 col-xl-4 d-none d-sm-block">
            <img class="section-img" src="{% static 'rmm_main/img/custom-design.jpg' %}" alt="Diseño totalmente personalizado"/>
        </div>
    </section>
    <section id="section-contact" class="row contact">
        <div class="col">
            <h2>Contacto</h2>
            <div class="container">
                <div id="contact-form-container" class="form-row alert alert-success">
                    <div class="col">
                        <span id="contact-form-message"></span>
                    </div>
                </div>
                <form method="POST" id="contact-form">
                {% csrf_token %}
                    <div class="form-group form-row">
                        <label for="inputName" class="col-sm-2 col-form-label" >Nombre</label>
                        <div class="col-sm-10">
                            <input id="inputName" class="form-control" name="{{ contact.name.html_name }}" aria-describedby="emialHelp" placeholder="Tu nombre" value="{{contact.name.value | default_if_none:''}}">
                        </div>
                    </div>
                    <div class="form-group form-row">
                        <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input id="inputEmail" class="form-control" name="{{ contact.email.html_name }}" type="email" placeholder="Tu email" value="{{contact.email.value| default_if_none:''}}">
                        </div>
                    </div>
                    <div class="form-group form-row">
                        <label for="inputMessage" class="col-sm-2 col-form-label">Mensaje</label>
                        <div class="col-sm-10">
                            <textarea id="inputMessage" class="form-control" name="{{ contact.message.html_name }}" placeholder="Tu mensaje" rows="3">{{contact.message.value | default_if_none:''}}</textarea>
                        </div>
                    </div>
                    <div class="form-group form-row">
                        <div class="col-sm-10 offset-sm-2">
                            <button type="submit" class="btn btn-dark">Contactar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</main>
{% endblock %}

{% block endscript %}
<script>
    $('#contact-form').on('submit', function(event){
        event.preventDefault();
        $.post( "{% url 'rmm_main:contact_submit' %}", $(this).serialize(), function(msg){
            // handle a successful response
            console.log(msg)
            if (msg['errcode'] == 0) {
                $("#contact-form-message").html(msg['message']);
                $("#contact-form-container").slideDown();
                setTimeout(function(){
                    $("#contact-form-container").slideUp();
                    $("#contact-form-message").html("");
                }, 10000);
            }
         });
    });

</script>
{% endblock %}

web_full/templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="es">
    <head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" /> 
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Web full</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <!-- Place favicon.ico in the root directory -->
        <link rel="stylesheet" href="{% static 'css/reset.min.css'%}">
		<link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'bootstrap-4.0.0-beta-dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

    </head>
    <body>
        {% block initscript %}{% endblock %}
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

        {% block navbar %}
		<nav class="navbar navbar-expand-md navbar-dark bg-dark">
			<a class="navbar-brand" href="#"><i class="fa fa-hashtag"></i>Web Full</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    	<span class="navbar-toggler-icon"></span>
		  	</button>

		  	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    	<ul class="navbar-nav mr-auto">
		      		<li class="nav-item active">
		        		<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
		      		</li>
				    <li class="nav-item">
				    	<a class="nav-link" href="#">Proyectos</a>
				    </li>
		      		<li class="nav-item">
		        		<a class="nav-link" href="#section-contact">Contacto</a>
		      		</li>
		    	</ul>
		  	</div>
		</nav>
        {% endblock %}

        {% block content %}{% endblock %}

        {% block footer %}
		<footer>
			<ul class="social">
				<li><i class="fa fa-twitter-square"></i></li>
				<li><i class="fa fa-facebook-square"></i></li>
				<li><i class="fa fa-instagram"></i></li>
				<li><i class="fa fa-youtube-square"></i></li>
				<li><i class="fa fa-google-plus-square"></i></li>
			</ul>
		</footer>
        {% endblock %}
	
		
        <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
        <script>window.jQuery || document.write('<script src="js/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="{% static 'bootstrap-4.0.0-beta-dist/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/plugins.min.js' %}"></script>
        <script src="{% static 'js/main.min.js' %}"></script>
        {% block endscript %}{% endblock %}
        <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
        <script>
            window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;
            ga('create','UA-XXXXX-Y','auto');ga('send','pageview')
        </script>
        <script src="https://www.google-analytics.com/analytics.js" async defer></script>

    </body>
</html>